version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: sale_saas_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - sale_saas_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  sale_saas_pgdata:
