// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sale_Saas.Infrastructure.Data;

#nullable disable

namespace Sale_Saas.Infrastructure.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240620061200_feature-sort")]
    partial class featuresort
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<bool?>("IsModified")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RolePositionId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.HasIndex("RolePositionId");

                    b.ToTable("ApplicationRoles", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.ApplicationRoleDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationRoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("FeatureId")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Permission")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationRoleId");

                    b.HasIndex("FeatureId");

                    b.HasIndex("MenuId");

                    b.ToTable("ApplicationRoleDetails", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.ApplicationRoleSaleKit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("Access")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ApplicationRoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("SaleKitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationRoleId");

                    b.HasIndex("SaleKitId");

                    b.ToTable("ApplicationRole_SaleKits");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<Guid?>("ApplicationUserStatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CurrentPosition")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Review")
                        .HasColumnType("text");

                    b.Property<bool?>("SMS")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserStatusId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("ApplicationUsers", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.ApplicationUserStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUserStatuses", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Benefit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BenefitStatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("MonthlySalary")
                        .HasColumnType("numeric");

                    b.Property<string>("RolePosition")
                        .HasColumnType("text");

                    b.Property<decimal?>("SuggestMonthlySalary")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SuggestTargetSalary")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SuggestTotalSalary")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TargetSalary")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalBenefit")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalSalary")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("BenefitStatusId");

                    b.ToTable("Benefits", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.BenefitHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BenefitId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("PreviousStatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedStatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("BenefitId");

                    b.HasIndex("PreviousStatusId");

                    b.HasIndex("UpdatedStatusId");

                    b.ToTable("BenefitHistories", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.BenefitStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BenefitStatuses", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid?>("ContractStatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContractStatusId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Contracts", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.ContractStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContractStatuses", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Fullname")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.EmployeeSalary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Dependent")
                        .HasColumnType("numeric");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("IncomeBeforeTax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IncomeNonTax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IncomeOther")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IncomeRecevied")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IncomeTax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Insurance")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<decimal?>("PersonalIncomeTax")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("EmployeeSalarys");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.EmployeeSalaryDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("text");

                    b.Property<decimal?>("IncomeEta")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IncomeReal")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("TimeSpent")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TypeCP")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmployeeSalaryDetails");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.EventLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Feature", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Sort")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.FeatureMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FeatureId")
                        .HasColumnType("text");

                    b.Property<Guid?>("MenuId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("MenuId");

                    b.ToTable("FeatureMenus", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Gains", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Archivement")
                        .HasColumnType("text");

                    b.Property<string>("Aspiration")
                        .HasColumnType("text");

                    b.Property<string>("Clubs")
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DayOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Degree")
                        .HasColumnType("text");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Dislike")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Family")
                        .HasColumnType("text");

                    b.Property<string>("FaviroteActivity")
                        .HasColumnType("text");

                    b.Property<string>("FormerJob")
                        .HasColumnType("text");

                    b.Property<string>("Habit")
                        .HasColumnType("text");

                    b.Property<string>("Hobby")
                        .HasColumnType("text");

                    b.Property<string>("Idol")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LongGoal")
                        .HasColumnType("text");

                    b.Property<string>("NativePlace")
                        .HasColumnType("text");

                    b.Property<string>("NearGoal")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<string>("PositionTerm")
                        .HasColumnType("text");

                    b.Property<Guid?>("RelationshipId")
                        .HasColumnType("uuid");

                    b.Property<string>("SchoolAndYear")
                        .HasColumnType("text");

                    b.Property<string>("Speciality")
                        .HasColumnType("text");

                    b.Property<string>("StrongPoint")
                        .HasColumnType("text");

                    b.Property<string>("WeakPoint")
                        .HasColumnType("text");

                    b.Property<string>("WeekendActivity")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Gains");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.GainsQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Code")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("GainsQuestions", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ActualKPI")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ActualPoint")
                        .HasColumnType("numeric");

                    b.Property<string>("Calculate")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Criteria")
                        .HasColumnType("text");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("GoalStatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Review")
                        .HasColumnType("text");

                    b.Property<string>("RolePosition")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SuggestEndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("SuggestTargetKPI")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SuggestTargetPoint")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TargetKPI")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TargetPoint")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("UserSuggestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GoalStatusId");

                    b.HasIndex("UserSuggestId");

                    b.ToTable("Goals", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.GoalStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GoalStatuses", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.MailServerInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("FromEmail")
                        .HasColumnType("text");

                    b.Property<string>("Hostname")
                        .HasColumnType("text");

                    b.Property<string>("IP")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MailService")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Port")
                        .HasColumnType("text");

                    b.Property<bool>("SSL")
                        .HasColumnType("boolean");

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.Property<string>("TenEmailGui")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MailServerInfos", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Extension")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FolderName")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("text");

                    b.Property<string>("ServerPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BreadcrumbNavigation")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActivite")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NameAction")
                        .HasColumnType("text");

                    b.Property<string>("NameController")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<string>("Parameter")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accountable")
                        .HasColumnType("text");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Beneficiary")
                        .HasColumnType("text");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CommissionMoney")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("EstimatedMoney")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("EstimatedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastTimeInteract")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Need")
                        .HasColumnType("text");

                    b.Property<string>("Opponent1")
                        .HasColumnType("text");

                    b.Property<string>("Opponent1Attribute")
                        .HasColumnType("text");

                    b.Property<string>("Opponent2")
                        .HasColumnType("text");

                    b.Property<string>("Opponent2Attribute")
                        .HasColumnType("text");

                    b.Property<Guid?>("OpportunityStatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("Strategy")
                        .HasColumnType("text");

                    b.Property<string>("TechnicalLead")
                        .HasColumnType("text");

                    b.Property<string>("WinningOppotunity")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("OpportunityStatusId");

                    b.ToTable("Opportunities", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.OpportunityHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Activity")
                        .HasColumnType("text");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Goal")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("OpportunityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("OpportunityId");

                    b.ToTable("OpportunityHistories", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.OpportunityStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OpportunityStatuses", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int?>("Point")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProjectStatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<string>("Service")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ContractId");

                    b.HasIndex("ProjectStatusId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.ProjectStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProjectStatuses", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ActualPoint")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CurrentRelationshipId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("GainsId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("Point")
                        .HasColumnType("numeric");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid?>("RelationshipStatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("RolePosition")
                        .HasColumnType("text");

                    b.Property<Guid?>("TargetRelationshipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CurrentRelationshipId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("GainsId")
                        .IsUnique();

                    b.HasIndex("RelationshipStatusId");

                    b.HasIndex("TargetRelationshipId");

                    b.ToTable("Relationships", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.RelationshipLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("PointFrom")
                        .HasColumnType("integer");

                    b.Property<int?>("PointTo")
                        .HasColumnType("integer");

                    b.Property<string>("Review")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RelationshipLevels", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.RelationshipStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RelationshipStatuses");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Relationship_GainsQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Answer")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("GainsQuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("RelationshipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GainsQuestionId");

                    b.HasIndex("RelationshipId");

                    b.ToTable("Relationship_GainsQuestions", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.RolePosition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsModified")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RolePositions");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.RolePositionFeatureMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FeatureMenuId")
                        .HasColumnType("uuid");

                    b.Property<string>("RolePositionId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FeatureMenuId");

                    b.HasIndex("RolePositionId");

                    b.ToTable("RolePositionFeatureMenus", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.SaleKit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Extension")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FolderName")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServerPath")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SaleKits");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Review")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sale_Saas.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.ApplicationRole", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.RolePosition", "RolePosition")
                        .WithMany("ApplicationRoles")
                        .HasForeignKey("RolePositionId");

                    b.Navigation("RolePosition");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.ApplicationRoleDetail", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.ApplicationRole", "ApplicationRole")
                        .WithMany("RoleDetails")
                        .HasForeignKey("ApplicationRoleId");

                    b.HasOne("Sale_Saas.Domain.Entities.Feature", "Feature")
                        .WithMany("RoleDetails")
                        .HasForeignKey("FeatureId");

                    b.HasOne("Sale_Saas.Domain.Entities.Menu", "Menu")
                        .WithMany("RoleDetails")
                        .HasForeignKey("MenuId");

                    b.Navigation("ApplicationRole");

                    b.Navigation("Feature");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.ApplicationRoleSaleKit", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.ApplicationRole", "ApplicationRole")
                        .WithMany("RoleSaleKits")
                        .HasForeignKey("ApplicationRoleId");

                    b.HasOne("Sale_Saas.Domain.Entities.SaleKit", "SaleKit")
                        .WithMany("RoleSaleKits")
                        .HasForeignKey("SaleKitId");

                    b.Navigation("ApplicationRole");

                    b.Navigation("SaleKit");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.ApplicationUserStatus", "ApplicationUserStatus")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("ApplicationUserStatusId");

                    b.Navigation("ApplicationUserStatus");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Benefit", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("Benefits")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Sale_Saas.Domain.Entities.BenefitStatus", "BenefitStatus")
                        .WithMany("Benefits")
                        .HasForeignKey("BenefitStatusId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("BenefitStatus");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.BenefitHistory", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("BenefitHistories")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Sale_Saas.Domain.Entities.Benefit", "Benefit")
                        .WithMany("BenefitHistories")
                        .HasForeignKey("BenefitId");

                    b.HasOne("Sale_Saas.Domain.Entities.BenefitStatus", "PreviousStatus")
                        .WithMany("BenefitHistoriesPrevious")
                        .HasForeignKey("PreviousStatusId");

                    b.HasOne("Sale_Saas.Domain.Entities.BenefitStatus", "UpdatedStatus")
                        .WithMany("BenefitHistoriesUpdated")
                        .HasForeignKey("UpdatedStatusId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Benefit");

                    b.Navigation("PreviousStatus");

                    b.Navigation("UpdatedStatus");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Contract", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.ContractStatus", "ContractStatus")
                        .WithMany("Contracts")
                        .HasForeignKey("ContractStatusId");

                    b.HasOne("Sale_Saas.Domain.Entities.Customer", "Customer")
                        .WithMany("Contracts")
                        .HasForeignKey("CustomerId");

                    b.Navigation("ContractStatus");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.EmployeeSalary", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.ApplicationRole", "Role")
                        .WithMany("EmployeeSalaries")
                        .HasForeignKey("RoleId");

                    b.HasOne("Sale_Saas.Domain.Entities.ApplicationUser", "User")
                        .WithMany("EmployeeSalaries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.EmployeeSalaryDetail", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.ApplicationUser", "User")
                        .WithMany("EmployeeSalaryDetails")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.FeatureMenu", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.Feature", "Feature")
                        .WithMany("FeatureMenus")
                        .HasForeignKey("FeatureId");

                    b.HasOne("Sale_Saas.Domain.Entities.Menu", "Menu")
                        .WithMany("FeatureMenus")
                        .HasForeignKey("MenuId");

                    b.Navigation("Feature");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Goal", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.GoalStatus", "GoalStatus")
                        .WithMany("Goals")
                        .HasForeignKey("GoalStatusId");

                    b.HasOne("Sale_Saas.Domain.Entities.ApplicationUser", "UserSuggest")
                        .WithMany("Goals")
                        .HasForeignKey("UserSuggestId");

                    b.Navigation("GoalStatus");

                    b.Navigation("UserSuggest");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Opportunity", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("Opportunities")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Sale_Saas.Domain.Entities.OpportunityStatus", "OpportunityStatus")
                        .WithMany("Opportunities")
                        .HasForeignKey("OpportunityStatusId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("OpportunityStatus");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.OpportunityHistory", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("OpportunityHistories")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Sale_Saas.Domain.Entities.Opportunity", "Opportunity")
                        .WithMany("OpportunityHistories")
                        .HasForeignKey("OpportunityId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Project", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("Projects")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Sale_Saas.Domain.Entities.Contract", "Contract")
                        .WithMany("Projects")
                        .HasForeignKey("ContractId");

                    b.HasOne("Sale_Saas.Domain.Entities.ProjectStatus", "ProjectStatus")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectStatusId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Contract");

                    b.Navigation("ProjectStatus");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Relationship", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("Relationships")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Sale_Saas.Domain.Entities.RelationshipLevel", "CurrentRelationship")
                        .WithMany("CurrentRelationships")
                        .HasForeignKey("CurrentRelationshipId");

                    b.HasOne("Sale_Saas.Domain.Entities.Customer", "Customer")
                        .WithMany("Relationships")
                        .HasForeignKey("CustomerId");

                    b.HasOne("Sale_Saas.Domain.Entities.Gains", "Gains")
                        .WithOne("Relationship")
                        .HasForeignKey("Sale_Saas.Domain.Entities.Relationship", "GainsId");

                    b.HasOne("Sale_Saas.Domain.Entities.RelationshipStatus", "RelationshipStatus")
                        .WithMany("Relationships")
                        .HasForeignKey("RelationshipStatusId");

                    b.HasOne("Sale_Saas.Domain.Entities.RelationshipLevel", "TargetRelationship")
                        .WithMany("TargetRelationships")
                        .HasForeignKey("TargetRelationshipId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("CurrentRelationship");

                    b.Navigation("Customer");

                    b.Navigation("Gains");

                    b.Navigation("RelationshipStatus");

                    b.Navigation("TargetRelationship");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Relationship_GainsQuestion", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.GainsQuestion", "GainsQuestion")
                        .WithMany("Relationship_GainsQuestion")
                        .HasForeignKey("GainsQuestionId");

                    b.HasOne("Sale_Saas.Domain.Entities.Relationship", "Relationship")
                        .WithMany("Relationship_GainsQuestion")
                        .HasForeignKey("RelationshipId");

                    b.Navigation("GainsQuestion");

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.RolePositionFeatureMenu", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.FeatureMenu", "FeatureMenu")
                        .WithMany("RolePositionFeatureMenus")
                        .HasForeignKey("FeatureMenuId");

                    b.HasOne("Sale_Saas.Domain.Entities.RolePosition", "RolePosition")
                        .WithMany("RolePositionFeatureMenus")
                        .HasForeignKey("RolePositionId");

                    b.Navigation("FeatureMenu");

                    b.Navigation("RolePosition");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.ApplicationRole", b =>
                {
                    b.Navigation("EmployeeSalaries");

                    b.Navigation("RoleDetails");

                    b.Navigation("RoleSaleKits");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("BenefitHistories");

                    b.Navigation("Benefits");

                    b.Navigation("EmployeeSalaries");

                    b.Navigation("EmployeeSalaryDetails");

                    b.Navigation("Goals");

                    b.Navigation("Opportunities");

                    b.Navigation("OpportunityHistories");

                    b.Navigation("Projects");

                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.ApplicationUserStatus", b =>
                {
                    b.Navigation("ApplicationUsers");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Benefit", b =>
                {
                    b.Navigation("BenefitHistories");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.BenefitStatus", b =>
                {
                    b.Navigation("BenefitHistoriesPrevious");

                    b.Navigation("BenefitHistoriesUpdated");

                    b.Navigation("Benefits");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Contract", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.ContractStatus", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Feature", b =>
                {
                    b.Navigation("FeatureMenus");

                    b.Navigation("RoleDetails");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.FeatureMenu", b =>
                {
                    b.Navigation("RolePositionFeatureMenus");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Gains", b =>
                {
                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.GainsQuestion", b =>
                {
                    b.Navigation("Relationship_GainsQuestion");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.GoalStatus", b =>
                {
                    b.Navigation("Goals");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Menu", b =>
                {
                    b.Navigation("FeatureMenus");

                    b.Navigation("RoleDetails");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Opportunity", b =>
                {
                    b.Navigation("OpportunityHistories");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.OpportunityStatus", b =>
                {
                    b.Navigation("Opportunities");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.ProjectStatus", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Relationship", b =>
                {
                    b.Navigation("Relationship_GainsQuestion");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.RelationshipLevel", b =>
                {
                    b.Navigation("CurrentRelationships");

                    b.Navigation("TargetRelationships");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.RelationshipStatus", b =>
                {
                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.RolePosition", b =>
                {
                    b.Navigation("ApplicationRoles");

                    b.Navigation("RolePositionFeatureMenus");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.SaleKit", b =>
                {
                    b.Navigation("RoleSaleKits");
                });
#pragma warning restore 612, 618
        }
    }
}
