<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sale_Saas.Domain\Sale_Saas.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\BenefitHistoryFeature\Commands\" />
    <Folder Include="Features\GainsSchoolFeature\Queries\" />
    <Folder Include="Features\RelationshipCustomerFeature\Commands\" />
    <Folder Include="Features\TargetFluctuationFeature\Queries\" />
  </ItemGroup>

</Project>
