// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sale_Saas.Infrastructure.Data;

#nullable disable

namespace Sale_Saas.Infrastructure.Migrations.TenantDb
{
    [DbContext(typeof(TenantDbContext))]
    partial class TenantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.GroupTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Color1")
                        .HasColumnType("text");

                    b.Property<string>("Color2")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Domain")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LimitChild")
                        .HasColumnType("integer");

                    b.Property<int?>("LimitUser")
                        .HasColumnType("integer");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GroupTenants", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.ModuleTenant", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("BreadcrumbNavigation")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("NameAction")
                        .HasColumnType("text");

                    b.Property<string>("NameController")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Parameter")
                        .HasColumnType("text");

                    b.Property<string>("ParentId")
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("ModuleTenants", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionId")
                        .HasColumnType("text");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Navigate")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("ReadFlag")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SeenDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("SeenFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("TenantId")
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("TenantId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("GroupTenantId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsActived")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("PlanServiceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Time")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupTenantId");

                    b.HasIndex("PlanServiceId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModuleTenantId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.OtpSend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ConfirmFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateInput")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultContent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OtpSends", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.PlanService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LimitChild")
                        .HasColumnType("integer");

                    b.Property<int?>("LimitUser")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Time")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PlanServices", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.PlanServiceModuleTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModuleTenantId")
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("PlanServiceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ModuleTenantId");

                    b.HasIndex("PlanServiceId");

                    b.ToTable("PlanServiceModuleTenants", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("GroupTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Host")
                        .HasColumnType("text");

                    b.Property<bool?>("IsAdminCreated")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubDomain")
                        .HasColumnType("text");

                    b.Property<string>("ThemeColor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupTenantId");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("ApplicationUserStatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("DeviceID")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("FullName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("GroupTenantId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Phone")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserStatusId");

                    b.HasIndex("GroupTenantId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.UserAdmin", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(125)
                        .HasColumnType("character varying(125)");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("character varying(125)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("character varying(125)");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("character varying(125)");

                    b.HasKey("UserName");

                    b.ToTable("UserAdmins", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.UserStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserStatus", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.UserTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("UserTenants", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.TrackingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("FunctionTime")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<float?>("ResponseTimeMin")
                        .HasColumnType("real");

                    b.Property<float?>("ResponseTimeSec")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TrackingLogs", (string)null);
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.Notification", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.Tenant.User", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Sale_Saas.Domain.Entities.Tenant.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.Order", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.Tenant.GroupTenant", "GroupTenant")
                        .WithMany("Orders")
                        .HasForeignKey("GroupTenantId");

                    b.HasOne("Sale_Saas.Domain.Entities.Tenant.PlanService", "PlanService")
                        .WithMany("Orders")
                        .HasForeignKey("PlanServiceId");

                    b.Navigation("GroupTenant");

                    b.Navigation("PlanService");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.OrderDetail", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.Tenant.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.PlanServiceModuleTenant", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.Tenant.ModuleTenant", "ModuleTenant")
                        .WithMany("PlanServiceModuleTenants")
                        .HasForeignKey("ModuleTenantId");

                    b.HasOne("Sale_Saas.Domain.Entities.Tenant.PlanService", "PlanService")
                        .WithMany("PlanServiceModuleTenants")
                        .HasForeignKey("PlanServiceId");

                    b.Navigation("ModuleTenant");

                    b.Navigation("PlanService");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.Tenant", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.Tenant.GroupTenant", "GroupTenant")
                        .WithMany("Tenants")
                        .HasForeignKey("GroupTenantId");

                    b.Navigation("GroupTenant");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.User", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.Tenant.UserStatus", "ApplicationUserStatus")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("ApplicationUserStatusId");

                    b.HasOne("Sale_Saas.Domain.Entities.Tenant.GroupTenant", "GroupTenant")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("GroupTenantId");

                    b.Navigation("ApplicationUserStatus");

                    b.Navigation("GroupTenant");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.UserTenant", b =>
                {
                    b.HasOne("Sale_Saas.Domain.Entities.Tenant.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.GroupTenant", b =>
                {
                    b.Navigation("ApplicationUsers");

                    b.Navigation("Orders");

                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.ModuleTenant", b =>
                {
                    b.Navigation("PlanServiceModuleTenants");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.PlanService", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("PlanServiceModuleTenants");
                });

            modelBuilder.Entity("Sale_Saas.Domain.Entities.Tenant.UserStatus", b =>
                {
                    b.Navigation("ApplicationUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
