<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Minio" Version="6.0.2" />
    <PackageReference Include="NETCore.MailKit" Version="2.1.0" />
    <PackageReference Include="Npgsql" Version="8.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.2" />
    <PackageReference Include="Serilog" Version="3.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sale_Saas.Application\Sale_Saas.Application.csproj" />
    <ProjectReference Include="..\Sale_Saas.Domain\Sale_Saas.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\ApplicationDb\" />
    <Folder Include="Migrations\TenantDb\" />
    <Folder Include="Sale_Saas\Infrastructure\Migrations\ApplicationDb\" />
    <Folder Include="Sale_Saas\Infrastructure\Migrations\TenantDb\" />
  </ItemGroup>

</Project>
